### ISSUE TITLE
Problem with include lines

### ISSUE THREAD

**Issue by jonsag** [JulianGmp/vscode-openscad-formatter#1]
Code before format:

```
//18650Battery.scad

// include some NOP scad libraries by nophead, https://github.com/nophead/NopSCADlib
include <../../OpenSCADlibraries/NopSCADlib/utils/core/core.scad>
include <../../OpenSCADlibraries/NopSCADlib/vitamins/batteries.scad>

// bcontact = ["bcontact", 9.33, 9.75, 0.4, 2.86, 6, [1.6, 3, 5], [4.5, batt_spring]];
my_bcontact = ["bcontact", contWidth, contHeight, contThick, termWidth, termLength,
	       [contPosHeight, contPosSmallDia, contPosLargeDia],
	       [contNegHeight, batt_spring]];

// S25R18650 = ["S25R18650", "Cell Samsung 25R 18650 LION",              65,   18.3, 13, 10,  0,   "MediumSeaGreen", [],                      0, bcontact];
my_18650 = ["18650 Li-ion 3.6V", "Cell Kjell & Co 2600mAh",
	     cellLength,   cellDia, 13, cellPosDia,  cellPosHeight,   "LightSkyBlue",
	    [],
	     0, bcontact];

module battery_n_terminals() {
  translate([0, 0, 0])
    rotate([0, 0, 0,]) {
    // 18650 cell
    battery(my_18650);

    // positive contact
    translate([0, 0, cellLength / 2 + posCOffset + compPosExtra])
      rotate([0, 180, 0])
      battery_contact(my_bcontact, true);
    
    // negative contact
    translate([0, 0, -cellLength / 2 + negCOffset - compNegExtra])
      battery_contact(my_bcontact, false);
    
  }
}
```

After format:

```
// 18650Battery.scad

// include some NOP scad libraries by nophead, https://github.com/nophead/NopSCADlib
include<../../ OpenSCADlibraries / NopSCADlib / utils / core / core.scad>
    include<../../ OpenSCADlibraries / NopSCADlib / vitamins / batteries.scad>

        // bcontact = ["bcontact", 9.33, 9.75, 0.4, 2.86, 6, [1.6, 3, 5], [4.5, batt_spring]];
        my_bcontact = [
	        "bcontact", contWidth, contHeight, contThick, termWidth, termLength,
	        [ contPosHeight, contPosSmallDia, contPosLargeDia ], [ contNegHeight, batt_spring ]
        ];

// S25R18650 = ["S25R18650", "Cell Samsung 25R 18650 LION",              65,   18.3, 13, 10,  0,   "MediumSeaGreen", [],
// 0, bcontact];
my_18650 = [
	"18650 Li-ion 3.6V", "Cell Kjell & Co 2600mAh", cellLength, cellDia, 13, cellPosDia, cellPosHeight, "LightSkyBlue",
	[], 0,
	bcontact
];

module battery_n_terminals()
{
	translate([ 0, 0, 0 ])
	rotate([
		0,
		0,
		0,
	])
	{
		// 18650 cell
		battery(my_18650);

		// positive contact
		translate([ 0, 0, cellLength / 2 + posCOffset + compPosExtra ])
		rotate([ 0, 180, 0 ])
		battery_contact(my_bcontact, true);

		// negative contact
		translate([ 0, 0, -cellLength / 2 + negCOffset - compNegExtra ])
		battery_contact(my_bcontact, false);
	}
}
```

Code is broken and renders incorrectly
> WARNING: Can't open include file '../../ OpenSCADlibraries / NopSCADlib / utils / core / core.scad'. 
> WARNING: Can't open include file '../../ OpenSCADlibraries / NopSCADlib / vitamins / batteries.scad'. 

/jon

**Comment by JulianGmp** [comment]
Well, here I was thinking "just pass it to clang-format and it'll work out", but it might not be this simple.

I took a look at [Maxattax97/openscad-format](https://github.com/Maxattax97/openscad-format), which seems to work around this issue by converting includes to a C-like include, formatting with clang-format, and reconverting the includes to openSCAD's format.
See [Maxattax97/openscad-format/index.js#L145](https://github.com/Maxattax97/openscad-format/blob/master/index.js#L145) line 145 to 163.

I will consider using that project as a foundation, instead of relying on clang-format directly, if I deem it stable enough (I've read some [worrying info](https://marketplace.visualstudio.com/items?itemName=AlexEaton.openscad-format&ssr=false#review-details) about it, which lead me to even make this project). 
Otherwise I will implement a similar solution.

As a workaround I only see two options
- manually fix the includes
- wrap the includes with `// clang-format off` and `// clang-format on` comments

Both of these options kinda suck, so sorry about that.
Thank you for the issue report nontheless.

**Comment by jonsag** [comment]
Actually I haven't had any good results with that formatter either, but that can be depending on me...
However the second solution you propose seems to be the the best one for now.

Thanks for looking into it!

**Comment by JulianGmp** [comment]
Do you mean good results as in good looking formatting, or was it broken?

Because if it's only the style then that can easily be changed with the style parameter from clang-format.
In this extension I defined the default to
`"{ BasedOnStyle: Microsoft, UseTab: ForIndentation, ColumnLimit: 120, StatementMacros: [rotate, translate] }"`.
You can override this with the extension options btw, but you should always include the StateMentMacros thing if you use rotate or translate without their curly brackets.

Now that look at this, there might be a config option to work around this issue, let me test this.

**Comment by JulianGmp** [comment]
Okay I looked into some of clang-format options, and I don't think I can solve this with just adding options to clang-format.

**Comment by esocode** [comment]
Just for info, I also tried various clang-format options without success, so at the moment there seems to be no alternative to the disable/enable comments around the include/use statements. But maybe a possible solution could be that the plugin could add these comments automatically around the imports? I haven't looked into how the code is passed to clang-format. To reduce the complexity this workaround could be limited to import statements at the beginning of the file.

**Comment by JulianGmp** [comment]
I finally got around to fixing this, sorry for the long wait.

I "solved" it by turning
```openscad
include <someOtherFile>
```
into
```c
// JulianGmp.openscad-formatter token
#include <someOtherFile>
```
and then back into its original after formatting.

a workaround that highly qualifies as virtual duct tape, but it seems to work fine. This would have been much easier if the `--lines` parameter in clang-format worked, but that one's currently bugged: https://github.com/llvm/llvm-project/issues/52993

If you could test this with your other files I would greatly appreciate it.

**Comment by esocode** [comment]
This works, but could you please apply the "duct tape" to the `use` statement too?

**Comment by JulianGmp** [comment]
> This works, but could you please apply the "duct tape" to the `use` statement too?

I didn't even know `use` was a thing. Thanks for mentioning it, I'll make myself some coffee and fix this later today.

**Comment by JulianGmp** [comment]
Alright I released a fix that does the same routine for `use` statements. The update should be up on the vscode marketplace soon.

**Comment by esocode** [comment]
Thanks, the new version is there, but still doesn't work correctly for `use`.  The code
```openscad
include <lib/box.scad>;
use <lib/box.scad>;
```
still receives the extra spaces during formatting:
```openscad
include <lib/box.scad>;
use < lib / box.scad > ;
```
The new version from today is active, I checked that.

**Comment by JulianGmp** [comment]
This really confused me, I tested this yesterday and it worked fine. Maybe this is different depending on clang-format versions? who knows.
In the end I realized the way I was working around was quite bad, I didn't exclude the use statements from formatting so clang-format still went at it.

I reworked how this functions and now I wrap both include and use statements like this:
```scad
// JulianGmp.openscad-formatter begin
// clang-format off
use <.....>
// clang-format on
// JulianGmp.openscad-formatter end
```
You will have to format any include and use statements manually as a result of this.
This really shows how hacky this entire extension is, but I hope that this makes it at least servicable for most people.

Also, if this pops up again (god I hope it won't), please open a new issue.
Cheers

**Comment by esocode** [comment]
Thanks, it works now with include and use. And thanks for hacking something like this together 😉, it's a really helpful extension,
